Create editorconfig
pdf-reports-parser/backend pull request #17
Opened 2022-03-17 17:24 UTC by RomanZorkin

Создал два файла :
.editorconfig - файл, который мне сформировал pycharm
.editorconfig.default - файл, который мы сделали на занятии

В файле из pycharm закоментил строки которых либо нет в дефолтном, но есть в пайчармовском, либо наоборот

2022-03-17 17:29 UTC, RomanZorkin commented on .editorconfig
> +# trim_trailing_whitespace = true # - no in pycharm
В pycharm автоматически при сохранении убираются висячие пробелы, наверное поэтому нет такой настройки

2022-03-18 07:29 UTC, RomanZorkin reviewed
Коментарии

2022-03-18 07:34 UTC, vppuzakov requested changes
👍 по комментам отлично, теперь удаляй .editorconfig и заменяй его нашим и готово

2022-03-18 07:34 UTC, vppuzakov commented on .editorconfig
> +# trim_trailing_whitespace = true # - no in pycharm
🔴  надо раскомментить

2022-03-18 07:34 UTC, vppuzakov commented on .editorconfig
> +# tab_width = 4 # - no in default
🔴 удалить

2022-03-18 07:34 UTC, vppuzakov commented on .editorconfig
> +# [*.csv] # - no in default
🔴 удалить - не должно быть закомментированных секций конфига или строк

2022-03-18 07:34 UTC, vppuzakov commented on .editorconfig
> +# max_line_length = 2147483647 # - no in default
🔴 удалить

2022-03-18 07:34 UTC, vppuzakov commented on .editorconfig
> +[{*.har,*.json}]
🔴 у нас нет вроде файлов .har

2022-03-18 07:34 UTC, vppuzakov commented on .editorconfig
> +[{*.yaml,*.yml}]
👍 их нет, но они вполне могут быть

2022-03-18 07:34 UTC, vppuzakov commented on .editorconfig
> +# [Makefile] # - no in pycharm
🔴 раскомментить, у нас есть такой файл и это очень важно для makefile

2022-03-18 07:48 UTC, vppuzakov approved these changes

2022-03-18 07:53 UTC, merged